(part "1751581"
    (packageRef "1751581")
    (interface
        (port "1" (symbPinId 1) (portName "1.1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "1.2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "2.1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "2.2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "3.1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "3.2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "4.1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "4.2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "5.1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "5.2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "6.1") (portType INOUT))
        (port "12" (symbPinId 12) (portName "6.2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "7.1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "7.2") (portType INOUT))
        (port "15" (symbPinId 15) (portName "8.1") (portType INOUT))
        (port "16" (symbPinId 16) (portName "8.2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "9.1") (portType INOUT))
        (port "18" (symbPinId 18) (portName "9.2") (portType INOUT))
        (port "19" (symbPinId 19) (portName "10.1") (portType INOUT))
        (port "20" (symbPinId 20) (portName "10.2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1751581")
    (property "Mouser_Part_Number" "651-1751581")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1751581?qs=5SfROSHwb7CCaVxuhSvzeQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "FFKDSA1/V1-5,08-10 - Printed circuit board terminal, nominal current: 15 A, rated voltage (III/2): 400 V, nominal cross section: 1.5 mm<sup>2</sup>, number of potentials: 10, number of rows: 1, number of positions per row: 10, product range: FFKDS(A)/V1, pitch: 5.08 mm, connection method: Push-in spring connection, mounting: Wave soldering, conductor/PCB connection direction: 90 , color: green, Pin layout: Linear pinning, Solder pin [P]: 3.4 mm, number of solder pins per potential: 2, type of packaging: pa")
    (property "Datasheet_Link" "https://www.phoenixcontact.com/en-us/products/printed-circuit-board-terminal-ffkdsa1v1-508-10-1751581?type=pdf")
    (property "symbolName1" "1751581")
)
